[project]
name = "three-body"
version = "0.1.0"
description = "A three-body problem visualization and simulation"
authors = ["Sigilante <neal@zorp.io>"]
license = "MIT"
repository = "https://github.com/sigilante/three-body"
homepage = "https://github.com/sigilante/three-body"
keywords = ["nockapp", "nockchain", "hoon", "physics", "simulation"]
edition = "2021"
template = "http-server"
